- slug: "adult-hiv"
  url: "https://bettercare.co.za/adult-hiv"
- slug: "breast-care"
  url: "https://bettercare.co.za/breast-care"
- slug: "child-and-adolescent-care-for-community-health-workers"
  url: "https://bettercare.co.za/child-and-adolescent-care-for-community-health-workers"
- slug: "child-healthcare"
  url: "https://bettercare.co.za/child-healthcare"
# - slug: "childhood-critical-care"
#   url: "https://bettercare.co.za/childhood-critical-care"
- slug: "childhood-hiv"
  url: "https://bettercare.co.za/childhood-hiv"
- slug: "childhood-tb"
  url: "https://bettercare.co.za/childhood-tb"
- slug: "congenital-disorders"
  url: "https://bettercare.co.za/congenital-disorders"
- slug: "covid-19-guide-for-community-health-workers"
  url: "https://bettercare.co.za/covid-19-guide-for-community-health-workers/"
- slug: "ebola-prevention-and-control"
  url: "https://bettercare.co.za/ebola-prevention-and-control"
- slug: "facilitators-guide"
  url: "https://bettercare.co.za/facilitators-guide"
- slug: "fetal-heart-rate-handbook"
  url: "https://bettercare.co.za/fetal-heart-rate-handbook"
- slug: "immunisations-a-guide-for-community-health-workers"
  url: "https://bettercare.co.za/learning-programmes/immunisations/"
- slug: "infection-prevention-and-control"
  url: "https://bettercare.co.za/infection-prevention-and-control"
- slug: "intrapartum-care"
  url: "https://bettercare.co.za/intrapartum-care"
- slug: "maternal-care"
  url: "https://bettercare.co.za/maternal-care"
- slug: "maternal-mental-health"
  url: "https://bettercare.co.za/maternal-mental-health"
- slug: "mental-health-and-wellbeing-a-guide-for-community-health-workers"
  url: "https://bettercare.co.za/mental-health-and-wellbeing"
- slug: "mother-and-baby-care-for-community-health-workers"
  url: "https://bettercare.co.za/mother-and-baby-care-for-community-health-workers"
- slug: "mother-and-baby-friendly-care"
  url: "https://bettercare.co.za/mother-and-baby-friendly-care"
- slug: "newborn-care"
  url: "https://bettercare.co.za/newborn-care"
- slug: "palliative-care-for-children"
  url: "https://bettercare.co.za/palliative-care-for-children"
- slug: "perinatal-hiv"
  url: "https://bettercare.co.za/perinatal-hiv"
- slug: "primary-maternal-care"
  url: "https://bettercare.co.za/primary-maternal-care"
- slug: "primary-newborn-care"
  url: "https://bettercare.co.za/primary-newborn-care"
- slug: "public-health"
  url: "https://bettercare.co.za/public-health"
- slug: "saving-mothers-and-babies"
  url: "https://bettercare.co.za/saving-mothers-and-babies"
- slug: "womens-health-care"
  url: "https://bettercare.co.za/womens-health-care"
