# Set site.output == "screen-pdf"
output: "screen-pdf"
# Set site.image-set == "images/screen-pdf"
image-set: "images/screen-pdf"
# Turn off documentation
collections:
  docs:
    output: false
exclude:
  # The usual excludes from _config.yml
  - run-linux.sh
  - run-mac.command
  - run-windows.bat
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  # Exclude files we don't need for print-pdf
  - /*/package.opf
  - /*/styles/print-pdf.scss
  - /*/styles/web.scss
  - /*/styles/epub.scss
  - /*/styles/app.scss
  - /*/index.md
  - /*/images/print-pdf
  - /*/images/web
  - /*/images/epub
  - /*/images/app
  # Books ---------------------------------
  # - adult-hiv
  # - breast-care
  # - catalogue
  # - child-healthcare
  # - childhood-critical-care
  # - childhood-hiv
  # - childhood-tb
  # - congenital-disorders
  # - covid-19-guide-for-community-health-workers
  # - ebola-prevention-and-control
  # - facilitators-guide
  # - fetal-heart-rate-handbook
  # - infection-prevention-and-control
  # - intrapartum-care
  # - maternal-care
  # - maternal-mental-health
  # - mental-health-and-wellbeing-a-guide-for-community-health-workers
  # - mother-and-baby-care-for-community-health-workers
  # - mother-and-baby-friendly-care
  # - newborn-care
  # - perinatal-hiv
  # - primary-maternal-care
  # - primary-newborn-care
  # - public-health
  # - samples
  # - saving-mothers-and-babies
  # - womens-health-care

# Populate the keep_files list for temporary faster builds
# or to keep previously generated files for other formats.
# The file path is relative to the site.output directory.
keep_files:
  # - adult-hiv
  # - breast-care
  # - catalogue
  # - child-healthcare
  # - childhood-critical-care
  # - childhood-hiv
  # - childhood-tb
  # - congenital-disorders
  # - covid-19-guide-for-community-health-workers
  # - ebola-prevention-and-control
  # - facilitators-guide
  # - fetal-heart-rate-handbook
  # - infection-prevention-and-control
  # - intrapartum-care
  # - maternal-care
  # - maternal-mental-health
  # - mental-health-and-wellbeing-a-guide-for-community-health-workers
  # - mother-and-baby-care-for-community-health-workers
  # - mother-and-baby-friendly-care
  # - newborn-care
  # - perinatal-hiv
  # - primary-maternal-care
  # - primary-newborn-care
  # - samples
  # - public-health
  # - saving-mothers-and-babies
  # - womens-health-care